### ISSUE TITLE
NewFileDialog with wx.FD_MULTIPLE - can't get []string of selected files

### ISSUE THREAD

**Issue by andrewarrow** [dontpanic92/wxGo#9]
trying to do:

```
  fd := wx.NewFileDialog(wx.NullWindow, "Select File(s)", "", "", "*", wx.FD_MULTIPLE,
    wx.DefaultPosition, wx.DefaultSize, "Open")
  fd.ShowModal()
  list := make([]string, 0)
  fd.GetFilenames(&list)
  fmt.Println(len(list))
```

```
fatal error: unexpected signal during runtime execution
[signal 0xa code=0x2 addr=0x5416138 pc=0x5416138]

runtime stack:
runtime.throw(0x4e0ea20, 0x2a)
	/usr/local/go/src/runtime/panic.go:527 +0x90
runtime.sigpanic()
	/usr/local/go/src/runtime/sigpanic_unix.go:12 +0x5a

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x44a1300, 0xc82004d9e8, 0x0)
	/usr/local/go/src/runtime/cgocall.go:120 +0x11b fp=0xc82004d9a0 sp=0xc82004d970
github.com/dontpanic92/wxGo/wx._Cfunc__wrap_FileDialog_GetFilenames_wx_c37cfa1345d8cfbe(0x6825800, 0xc820078060)
	??:0 +0x35 fp=0xc82004d9e8 sp=0xc82004d9a0
github.com/dontpanic92/wxGo/wx.SwigcptrFileDialog.GetFilenames(0x6825800, 0xc820078060)
	/Users/aa/dev/src/github.com/dontpanic92/wxGo/wx/wx_darwin.go:100730 +0x2b fp=0xc82004da00 sp=0xc82004d9e8
github.com/dontpanic92/wxGo/wx.(*SwigcptrFileDialog).GetFilenames(0xc820064750, 0xc820078060)
	<autogenerated>:15872 +0x99 fp=0xc82004da38 sp=0xc82004da00
```

**Comment by dontpanic92** [comment]
It is a typemap issue. I will fix it asap.

**Comment by andrewarrow** [comment]
awesome, thank u!

**Comment by dontpanic92** [comment]
Should be fixed now.

**Comment by andrewarrow** [comment]
works perfect, closing issue
